---
- name: Formatting data structures
  hosts: localhost
  vars:

    list1:
      - apple
      - orange
      - banana
      - lemmon

    list2:
      - kiwi
      - orange
      - feijoa
      - grape
      - apple

    list3: "{{ list1 + list2 }}"
    dict1:
      day: Wednesday
      month: February
      year: 2018

    security_groups:
      - {name: "my-sg-1", port: 22, remote_ip_address: "192.168.1.15/32"}
      - {name: "my-sg-2", port: 80, remote_ip_address: "192.168.1.0/24"}
      - {name: "my-sg-2", port: 443, remote_ip_address: "192.168.1.0/24"}
      - {name: "my-sg-3", port: 5000, remote_ip_address: "192.168.1.1/32", end_port: 5010}
      - {name: "my-sg-3", port: 8000, remote_ip_address: "192.168.1.1/32", end_port: 8010}

    validip: 153.24.54.23
    invalidip: 122.44.33.22.44
    myipv4: 192.168.1.2
    myipv6: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
    basefilename: "{{ ansible_env.HOME }}/introduction-to-ansible/sample-code/ansible.cfg.example"


  tasks:
    


