- name: Create cloud hosts file
  hosts: localhost
  tasks:
    - debug:
        var: prefix | mandatory

    - name: Create ansible directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.ansible/inventory"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"

    - name: Create host file for cluster
      template:
        src: templates/hosts.j2
        dest: "{{ lookup('env', 'HOME') }}/.ansible/inventory/cloud-hosts"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}" 
        mode: '0644'


- name: Populate cloud configuration
  hosts: localhost
  roles:
    - role: openstack-cloud

