---


- name: Basic host setup
  hosts: cluster
  become: true
  gather_facts: false
  tasks:

    - name: Update apt cache
      raw: apt update -y

    - name: Install python
      raw: >
        which python || apt-get install -y python && echo 'installed'
      register: python
      changed_when: python.stdout == 'installed'

    - name: Add NZ locale to all instances
      locale_gen:
        name: en_NZ.UTF-8
        state: present

- name: Set local host website
  hosts: localhost
  become: true
  tasks:
    - name: Add website address for local site
      blockinfile:
        path: /etc/hosts
        marker: '#{mark} Ansible block for {{ hostvars[groups.web[0]].domain_name }}'
        block: |
          127.0.0.1  {{ hostvars[groups.web[0]].domain_name }}
          


