- name: Handler exercise for nginx
  hosts: web
  become: true
  tasks:

    - name: Set up nginx task 1
      debug:
        msg: This task sets up nginx config
      changed_when: nginx_config_changed | default(false)


    - name: Set up nginx task 2
      debug:
        msg: This task sets up nginx crt
      changed_when: nginx_crt_changed | default(false)

    - name: Set up nginx task 3
      debug:
        msg: This task sets up nginx key
      changed_when: nginx_key_changed | default(false)


    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
