---

- hosts: localhost

  vars:
    foo: bar

  tasks:

  - apt: name=mtr
    become: true

  - template: src=templates/example-template.j2 dest=/tmp/template-example.txt mode=0644

  - debug: msg="This always displays"

  - command: cp files/copy-example.txt /tmp/

  - shell: echo "xyzzy" >> /tmp/copy-example.txt
