---
- src: https://github.com/heytrav/ansible-setup-openstack.git
  scm: git
  name: cloud-config
  version: master

- src: https://github.com/heytrav/ansible-nodejs.git
  scm: git
  name: trainingpc-nodejs
  version: master

- src: https://github.com/heytrav/ansible-vagrant.git
  scm: git
  name: training-vagrant
  version: master
