---

- name: Configure training machines for the Catalyst Cloud course
  hosts: localhost
  tags: 
    - initial
  tasks:

    - name: Replace train users bashrc with a custom version
      template:
        src: templates/train.bashrc.j2
        dest: "/home/{{ ssh_user }}/.bashrc"
        mode: 0644

    - name: Create .ssh/config file
      file:
        path: "/home/{{ ssh_user }}/.ssh/config"
        state: touch
        owner: "{{ ssh_user }}"
        group:  "{{ ssh_user }}"
        mode: 0644

    - name: Create SSH key for user train
      user: 
        name: "{{ ssh_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: "/home/{{ ssh_user }}/.ssh/id_rsa"



- name: Set up reveal presentation
  hosts: localhost
  tags: setup
  roles:
    - role: trainingpc-nodejs
  post_tasks:

    - name: Set up reveal presentation
      command: npm install
      args:
        chdir: "{{ ansible_env.HOME }}/introduction-to-ansible/slides"
        creates: node_modules

- name: Set up machines for running vagrant
  hosts: localhost
  roles:
    - role: trainingpc-vagrant
  tags:
    - vagrant
