---

- name: Set up application
  hosts: myserver
  become: true
  tasks:

    - name: Install packages needed for application
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python-dev
        - python-virtualenv


    - name: Checkout application from git
      git:
        repo: https://github.com/heytrav/counter-app.git
        dest: "{{ app_directory }}"
        version: "{{ app_version | default('master') }}"

    - name: Install python libraries
      pip:
        requirements: "{{ app_directory }}/requirements.txt"
        virtualenv: "{{ app_directory }}/venv"
        virtualenv_python: python3
          

    - name: Add systemd config
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
        owner: root
        group: root
        mode: 0644

    - name: Enable gunicorn service
      systemd:
        name: gunicorn.service
        enabled: true

    - name: Reload gunicorn
      systemd:
        name: gunicorn
        state: reloaded

    - name: Start the gunicorn service
      systemd:
        name: gunicorn
        state: started
